# fly.toml file generated for controle-financeiro on 2023-04-09T19:36:10-03:00

app = "controle-financeiro"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "gru"
processes = []

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  APP_NAME = "Controle Financeiro"
  APP_URL = "https://controle-financeiro.fly.dev"
  DB_CONNECTION = "mysql"
  DB_HOST = "aws.connect.psdb.cloud"
  DB_DATABASE= "db_controle_financeiro"
  MYSQL_ATTR_SSL_CA="/etc/ssl/certs/ca-certificates.crt"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
